# Generated by Django 3.0.6 on 2020-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('is_pro', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
