# Generated by Django 3.0.6 on 2020-05-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200523_0106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceprovider',
            table='ServiceProvider',
        ),
    ]
