# Generated by Django 3.0.6 on 2020-05-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20200523_0111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promoapplied',
            table='PromoApplied',
        ),
        migrations.AlterModelTable(
            name='promoincludes',
            table='PromoIncludes',
        ),
    ]
